name: Build Test
on:
 [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v3

     - name: setup-node
       uses: actions/setup-node@v3
       with:
         node-version: 16
         cache: yarn

     - name: yarn-install
       run: yarn

     - name: app-build
       run: yarn build
       
     - name: app-start
       run: yarn start
